= Customizing the user context menu

== Customizing the user context menu

The user context menu can be customized by intercepting the `AdminMenuEvent` and customizing the `UserContextAdminMenuGroup#MENU_PATH` group.

== Customizing the display name or avatar.
Admin web provides a user context menu at the top right navigation bar of the interface.
This settings menu by default shows the current logged in user and provides the option to log out.
It is configured to be the last menu item in the navigation bar.

The user context menu by default shows a user icon followed by the name of the current principal.
By intercepting the `UserContextAdminMenuGroup` event, the display name and avatar of the authenticated principal can be customized.
A `UserContextAdminMenuGroup` has the following settings:

[cols="1,1,2", options="header"]
|===

| Property
| Default value
| Description

| displayName
| CurrentSecurityPrincipalProxy#getPrincipalName
| Renders the name of the authenticated principal if a name is present.
If the name is empty, no name will be rendered.

| thumbnailUrl
| none
| Renders the avatar of the authenticated principal if a url is provided.
If the url is empty, a user icon is rendered instead.

|===

The styling of the context menu can be customized as follows:

* The context menu has a `admin-nav-user-context` class.
** If an avatar is available, the class `with-thumbnail` will be added as well.
* If an avatar is available, it will have the class `admin-nav-user-context-thumbnail`

The configured `UserContextAdminMenuGroup` will also be available on the context menu under the `UserContextAdminMenuGroup.ATTRIBUTE` attribute.